/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace PriceManager
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class BidOper : TBase
  {

    public string Ownerid { get; set; }

    public string Deptid { get; set; }

    public string OutGoodsID { get; set; }

    public string CmsSkuID { get; set; }

    public string BidPrice { get; set; }

    public string Empid { get; set; }

    public BidOper() {
    }

    public BidOper(string ownerid, string deptid, string outGoodsID, string cmsSkuID, string bidPrice, string empid) : this() {
      this.Ownerid = ownerid;
      this.Deptid = deptid;
      this.OutGoodsID = outGoodsID;
      this.CmsSkuID = cmsSkuID;
      this.BidPrice = bidPrice;
      this.Empid = empid;
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_ownerid = false;
        bool isset_deptid = false;
        bool isset_outGoodsID = false;
        bool isset_cmsSkuID = false;
        bool isset_bidPrice = false;
        bool isset_empid = false;
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String) {
                Ownerid = iprot.ReadString();
                isset_ownerid = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.String) {
                Deptid = iprot.ReadString();
                isset_deptid = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.String) {
                OutGoodsID = iprot.ReadString();
                isset_outGoodsID = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 4:
              if (field.Type == TType.String) {
                CmsSkuID = iprot.ReadString();
                isset_cmsSkuID = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 5:
              if (field.Type == TType.String) {
                BidPrice = iprot.ReadString();
                isset_bidPrice = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 6:
              if (field.Type == TType.String) {
                Empid = iprot.ReadString();
                isset_empid = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
        if (!isset_ownerid)
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        if (!isset_deptid)
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        if (!isset_outGoodsID)
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        if (!isset_cmsSkuID)
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        if (!isset_bidPrice)
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        if (!isset_empid)
          throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("BidOper");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        field.Name = "ownerid";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Ownerid);
        oprot.WriteFieldEnd();
        field.Name = "deptid";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Deptid);
        oprot.WriteFieldEnd();
        field.Name = "outGoodsID";
        field.Type = TType.String;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(OutGoodsID);
        oprot.WriteFieldEnd();
        field.Name = "cmsSkuID";
        field.Type = TType.String;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(CmsSkuID);
        oprot.WriteFieldEnd();
        field.Name = "bidPrice";
        field.Type = TType.String;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(BidPrice);
        oprot.WriteFieldEnd();
        field.Name = "empid";
        field.Type = TType.String;
        field.ID = 6;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Empid);
        oprot.WriteFieldEnd();
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("BidOper(");
      __sb.Append(", Ownerid: ");
      __sb.Append(Ownerid);
      __sb.Append(", Deptid: ");
      __sb.Append(Deptid);
      __sb.Append(", OutGoodsID: ");
      __sb.Append(OutGoodsID);
      __sb.Append(", CmsSkuID: ");
      __sb.Append(CmsSkuID);
      __sb.Append(", BidPrice: ");
      __sb.Append(BidPrice);
      __sb.Append(", Empid: ");
      __sb.Append(Empid);
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
