/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace PriceManager
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class DeptInfo : TBase
  {

    public string Deptid { get; set; }

    public string Deptname { get; set; }

    public string Ownerid { get; set; }

    public DeptInfo() {
    }

    public DeptInfo(string deptid, string deptname, string ownerid) : this() {
      this.Deptid = deptid;
      this.Deptname = deptname;
      this.Ownerid = ownerid;
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_deptid = false;
        bool isset_deptname = false;
        bool isset_ownerid = false;
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String) {
                Deptid = iprot.ReadString();
                isset_deptid = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.String) {
                Deptname = iprot.ReadString();
                isset_deptname = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.String) {
                Ownerid = iprot.ReadString();
                isset_ownerid = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
        if (!isset_deptid)
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        if (!isset_deptname)
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        if (!isset_ownerid)
          throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("DeptInfo");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        field.Name = "deptid";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Deptid);
        oprot.WriteFieldEnd();
        field.Name = "deptname";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Deptname);
        oprot.WriteFieldEnd();
        field.Name = "ownerid";
        field.Type = TType.String;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Ownerid);
        oprot.WriteFieldEnd();
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("DeptInfo(");
      __sb.Append(", Deptid: ");
      __sb.Append(Deptid);
      __sb.Append(", Deptname: ");
      __sb.Append(Deptname);
      __sb.Append(", Ownerid: ");
      __sb.Append(Ownerid);
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
