/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace PriceManager
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class RespPriceInfo : TBase
  {
    private List<SkuPrice> _priceList;

    public InquiryOrder InquiryOrder { get; set; }

    public SkuInfo SkuInfo { get; set; }

    public List<SkuPrice> PriceList
    {
      get
      {
        return _priceList;
      }
      set
      {
        __isset.priceList = true;
        this._priceList = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool priceList;
    }

    public RespPriceInfo() {
    }

    public RespPriceInfo(InquiryOrder inquiryOrder, SkuInfo skuInfo) : this() {
      this.InquiryOrder = inquiryOrder;
      this.SkuInfo = skuInfo;
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_inquiryOrder = false;
        bool isset_skuInfo = false;
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Struct) {
                InquiryOrder = new InquiryOrder();
                InquiryOrder.Read(iprot);
                isset_inquiryOrder = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.Struct) {
                SkuInfo = new SkuInfo();
                SkuInfo.Read(iprot);
                isset_skuInfo = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.List) {
                {
                  PriceList = new List<SkuPrice>();
                  TList _list0 = iprot.ReadListBegin();
                  for( int _i1 = 0; _i1 < _list0.Count; ++_i1)
                  {
                    SkuPrice _elem2;
                    _elem2 = new SkuPrice();
                    _elem2.Read(iprot);
                    PriceList.Add(_elem2);
                  }
                  iprot.ReadListEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
        if (!isset_inquiryOrder)
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        if (!isset_skuInfo)
          throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("RespPriceInfo");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        field.Name = "inquiryOrder";
        field.Type = TType.Struct;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        InquiryOrder.Write(oprot);
        oprot.WriteFieldEnd();
        field.Name = "skuInfo";
        field.Type = TType.Struct;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        SkuInfo.Write(oprot);
        oprot.WriteFieldEnd();
        if (PriceList != null && __isset.priceList) {
          field.Name = "priceList";
          field.Type = TType.List;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteListBegin(new TList(TType.Struct, PriceList.Count));
            foreach (SkuPrice _iter3 in PriceList)
            {
              _iter3.Write(oprot);
            }
            oprot.WriteListEnd();
          }
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("RespPriceInfo(");
      __sb.Append(", InquiryOrder: ");
      __sb.Append(InquiryOrder== null ? "<null>" : InquiryOrder.ToString());
      __sb.Append(", SkuInfo: ");
      __sb.Append(SkuInfo== null ? "<null>" : SkuInfo.ToString());
      if (PriceList != null && __isset.priceList) {
        __sb.Append(", PriceList: ");
        __sb.Append(PriceList);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
