/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace PriceManager
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ReturnMessage : TException, TBase
  {
    private int _retCode;
    private string _retMessage;

    public int RetCode
    {
      get
      {
        return _retCode;
      }
      set
      {
        __isset.retCode = true;
        this._retCode = value;
      }
    }

    public string RetMessage
    {
      get
      {
        return _retMessage;
      }
      set
      {
        __isset.retMessage = true;
        this._retMessage = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool retCode;
      public bool retMessage;
    }

    public ReturnMessage() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32) {
                RetCode = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.String) {
                RetMessage = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("ReturnMessage");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.retCode) {
          field.Name = "retCode";
          field.Type = TType.I32;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(RetCode);
          oprot.WriteFieldEnd();
        }
        if (RetMessage != null && __isset.retMessage) {
          field.Name = "retMessage";
          field.Type = TType.String;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(RetMessage);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("ReturnMessage(");
      bool __first = true;
      if (__isset.retCode) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("RetCode: ");
        __sb.Append(RetCode);
      }
      if (RetMessage != null && __isset.retMessage) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("RetMessage: ");
        __sb.Append(RetMessage);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
