/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace PriceManager
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class SkuInfo : TBase
  {

    public string OutGoodsID { get; set; }

    public string GoodsStatus { get; set; }

    public SkuInfo() {
    }

    public SkuInfo(string outGoodsID, string goodsStatus) : this() {
      this.OutGoodsID = outGoodsID;
      this.GoodsStatus = goodsStatus;
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_outGoodsID = false;
        bool isset_goodsStatus = false;
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String) {
                OutGoodsID = iprot.ReadString();
                isset_outGoodsID = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.String) {
                GoodsStatus = iprot.ReadString();
                isset_goodsStatus = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
        if (!isset_outGoodsID)
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        if (!isset_goodsStatus)
          throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("SkuInfo");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        field.Name = "outGoodsID";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(OutGoodsID);
        oprot.WriteFieldEnd();
        field.Name = "goodsStatus";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(GoodsStatus);
        oprot.WriteFieldEnd();
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("SkuInfo(");
      __sb.Append(", OutGoodsID: ");
      __sb.Append(OutGoodsID);
      __sb.Append(", GoodsStatus: ");
      __sb.Append(GoodsStatus);
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
